name: Test
on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  bun install
            - name: Run tests
              run: |
                  bun run test
